ansible_become_password: "{{ lookup('env', 'PASSWORD') }}"
system_enable_packages: "{{ lookup('env', 'ENABLE_PACKAGES')  | default('true')  | bool }}"
system_enable_users:    "{{ lookup('env', 'ENABLE_USERS')     | default('false') | bool }}"
system_enable_hardening: "{{ lookup('env', 'ENABLE_HARDENING') | default('false') | bool }}"
system_enable_firewall: "{{ lookup('env', 'ENABLE_FIREWALL')  | default('false') | bool }}"
system_enable_dirs:     "{{ lookup('env', 'ENABLE_DIRS')      | default('true')  | bool }}"
