$ANSIBLE_VAULT;1.1;AES256
30326364313834633432373237643264303437633664363465303837353237623032383334316539
6638646431396264336135313665383339343066363565340a333762333062373862393831643066
65396531613332353033616230353030356633323962373838306533376633316532313235393435
3239313563616331630a376636313037613763396364633534353166653363383239393033633035
64636663643362323632656639383333366539613639373736626531663132316233303065393433
34323536313565313866663862336463663435613038326335323834616332633533396462356362
666631393265386561353731303235653561
