---
- name: Ansible VM Setup Playbook
  hosts: kube8master-host         # The group from your inventory
  become: yes                     # Allow sudo for all tasks
  become_method: sudo
  become_user: root

  roles:
    - python                      # This triggers the entire role
