---
# Install required Python packages
- name: Install required Python packages
  include_tasks: install_dependencies.yml   # Load Python install tasks

# Manage the Apache webserver
- name: Manage Apache HTTP server
  include_tasks: apache.yml                 # Load Apache tasks

# Create your custom project directory
- name: Create app directory
  file:
    path: "{{ app_dir }}"        # Comes from defaults/main.yml
    state: directory             # Create directory
    mode: '0755'                 # Permissions
