kube8master-host:
  hosts:
    dynamic_host:
      ansible_host: "{{ lookup('env', 'HOST_IP') }}"
      ansible_user: "{{ lookup('env', 'HOST_USER') }}"
      ansible_ssh_private_key_file: "{{ lookup('env', 'HOST_KEY') }}"
